export enum NAMES {
  SET_BALANCE = 'SET_BALANCE',
  SET_LOADING = 'SET_LOADING',
  SET_BITCOIN_FEES = 'SET_BITCOIN_FEES',
  SET_RATES = 'SET_RATES',
  SET_VARIATION = 'SET_VARIATION',
  SET_TRANSACTIONS = 'SET_TRANSACTIONS',
}
